### ISSUE TITLE
Performance should be way better

### ISSUE THREAD

**Issue by lottebijlsma** [lottebijlsma/lottebijlsma.github.io#35]
- Images loading time
- Thumbnails
- ...

**Comment by thibmaek** [comment]
It might be insightful to run a [Google PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/) on https://lottebijlsma.be and post results (in a screenshot or link) here.

**Comment by thibmaek** [comment]
https://github.com/robwierzbowski/jekyll-picture-tag

**Comment by thibmaek** [comment]
Things are optimised on the Cloudflare side. Should do a rerun of a Lighthouse report to see if it improved.
