### ISSUE TITLE
Change icon to new site icon

### ISSUE THREAD

**Issue by thibmaek** [lottebijlsma/lottebijlsma.github.io#70]
Would change the eye icon to the newer pink circle for favicon / ati.

**Comment by thibmaek** [comment]
Was not what I meant, I meant change the favicon or apple touch icon to the new pink one. Not header content

**Comment by thibmaek** [comment]
![image](https://cloud.githubusercontent.com/assets/6213695/21541926/a629c914-cdba-11e6-82c3-603c505051c0.png)

**Comment by lottebijlsma** [comment]
<img width="262" alt="screen shot 2016-12-29 at 11 34 53" src="https://cloud.githubusercontent.com/assets/20845812/21541957/e1e2729e-cdba-11e6-9951-22063ecc19fc.png">
