### ISSUE TITLE
Match header icon to category

### ISSUE THREAD

**Issue by thibmaek** [lottebijlsma/lottebijlsma.github.io#73]
Would be cool if you could match the header icon to the category, for example:

![image](https://cloud.githubusercontent.com/assets/6213695/21542063/a3c627ac-cdbb-11e6-80d6-9d245d381cee.png)

In the above image change the pin to code brackets or a terminal icon.
Could easily be done by just writing an if/else or switch statement in Liquid and then filling icon accordingly.

**Comment by lottebijlsma** [comment]
Yes, that would be cool. Currently it's just a SVG so I'll look at it if I have the time (or if you don't have anything to do? 😋)

**Comment by lottebijlsma** [comment]
Since design has changed, I'm closing this 👋
